version: '3.8'

services:
  sensor-db:
    image: mysql:8.0
    container_name: sensor-db
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rD
      MYSQL_DATABASE: SensorDb
      MYSQL_USER: sensoruser
      MYSQL_PASSWORD: sensorpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sensor-net

  sensor-api:
    build:
      context: ./SensorApi
      dockerfile: Dockerfile
    container_name: sensor-api
    depends_on:
      - sensor-db
    platform: linux/amd64
    environment:
      - ConnectionStrings__DefaultConnection=${SENSOR_DB_CONSTR}
      - ASPNETCORE_URLS=http://+:5287
    ports:
      - "5287:5287"
    networks:
      - sensor-net

  sensor-ui:
    build:
      context: ./sensor-ui
      dockerfile: Dockerfile
    container_name: sensor-ui
    ports:
      - "80:80"
    depends_on:
      - sensor-api
    networks:
      - sensor-net
  
  ai-agent:
    build:
      context: ./ai-agent
    container_name: ai-agent
    ports:
      - "1234:1234"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  sensor-net:
